name: "🧩 Feature Request"
description: "Suggest a new feature or an improvement for FilmOptima. Help us make it better!"
title: "[FR]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new feature! This feedback is invaluable for shaping the future of FilmOptima.
        **Please search the existing issues first to see if your idea has already been suggested. If it has, please add a 👍 reaction or a comment with your use case.**

  - type: input
    id: feature-name
    attributes:
      label: "Feature Name"
      description: "A clear and concise name for the feature."
      placeholder: "e.g., 'Multi-Objective Optimization Goals'"
    validations:
      required: true

  - type: textarea
    id: problem-motivation
    attributes:
      label: "Problem & Motivation"
      description: "Is your feature request related to a problem? Please describe the pain point you are facing in your current workflow. Why is this feature important to you?"
      placeholder: |
        Currently, to achieve [X], I have to [describe manual workaround]. This is inefficient because...
        This problem is critical for my work on [type of design] because...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: "Describe what you want to happen. How should this new feature work? Be as specific as you can."
      placeholder: |
        I believe this could be solved if FilmOptima could...
        Ideally, the interface would have a new section where I could...
        The software should allow me to define...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Describe any alternative solutions or workarounds you've considered or are currently using."
      placeholder: "The current workaround is to export the data and use [external tool], which is slow and error-prone."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Impact (For You)"
      description: "How important is this feature for your workflow?"
      options:
        - "Low (Nice to have, but not a blocker)"
        - "Medium (Important improvement for efficiency)"
        - "High (Critical for my current projects/workflow)"
        - "Essential (I cannot adopt FilmOptima without this)"
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: "Specific Use Cases"
      description: "List 1-3 specific examples of where and how you would use this feature. The more concrete, the better."
      placeholder: |
        1. When designing a broadband AR coating, I would use this to...
        2. This would help me automate the process of...
        3. For my team, it would allow us to...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context, screenshots, mock-ups, or links about the feature request here. You can drag and drop images."
      placeholder: "Here is a sketch of how the interface might look..."
    validations:
      required: false
